filter:
    excluded_paths:
        - 'tests/*'
        - "src/database/migrations/*"
        - "src/resources/*"
checks:
    php: true
    javascript: false
coding_style:
    php:
      spaces:
        around_operators:
            concatenation: true
            negation: true