language: php

php:
  - 7.0
  - nightly

matrix:
  fast_finish: true

services:
  - mysql

before_script:
  - mysql -e 'create database build_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose